apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-ventas-web
  namespace: "2023205111"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-ventas-web
  template:
    metadata:
      labels:
        app: smart-ventas-web
    spec:
      hostNetwork: true
      dnsPolicy: Default
      containers:
      - name: web
        image: zaynok/smart-ventas-web:v26
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "miguelangelxd669@gmail.com"
        - name: SMTP_PASS
          value: "pkxc pdgk ihys iihg"
        - name: SMTP_FROM
          value: "\"SmartVentas\" <miguelangelxd669@gmail.com>"
        - name: SMTP_SECURE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: smart-ventas-web-svc
  namespace: "2023205111"
spec:
  type: NodePort
  selector:
    app: smart-ventas-web
  ports:
  - port: 3000
    targetPort: 3000
